In [1]:
import numpy as np

In [2]:
# one dimension array
arr = np.array([1,2,3,4,5])

# type of array
print(type(arr))
print(arr[0])

<class 'numpy.ndarray'>
1


In [3]:
# two dimension array
# array index starts at 0 
twoarr = np.array([[1,2,3],[4,5,6]])
twoarr

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# check dimensions
print(arr.ndim)
print(twoarr.ndim)
print(arr.shape)

1
2
(5,)


In [13]:
# filled with zeroes   
np.zeros(2)

array([0., 0.])

In [14]:
# filled with ones
np.ones(1)

array([1.])

In [15]:
np.empty(3)

array([4.24399158e-314, 8.48798317e-314, 1.27319747e-313])

In [16]:
np.arange(4)
# starts with 0
# not include 4

array([0, 1, 2, 3])

In [17]:
np.arange(1,5)

array([1, 2, 3, 4])